name: Test git-update-submodules
on:
  push:
    branches: [ main, test ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'git-update-submodules ref to install'
      init:
        description: "Initial commit SHA to initialize this test's branch to"
        default: 'b72d4de78127f569d106e665767298a5004baffa'
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  test:
    name: Test git-update-submodules
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: |
          echo "REF=${{ inputs.ref || (github.event.pull_request && github.head_ref || github.ref_name) }}" >> $GITHUB_ENV
          echo "branch=test-${{ github.run_id }}" >> $GITHUB_ENV
      - name: Install git-update-submodules
        run: pip install git+https://github.com/$GITHUB_REPOSITORY@$REF
      - name: Initialize test branch
        uses: runsascoded/tmp-branch-action@main
        with:
          branch: ${{ env.branch }}
          sha: ${{ inputs.init || 'b72d4de78127f569d106e665767298a5004baffa' }}
      - name: Update submodules
        run: github-update-submodules -b$branch
      - name: Verify submodule updates
        run: |
          echo "Branch $branch"
          commit="$(gh api /repos/$GITHUB_REPOSITORY/git/ref/heads/$branch | jq -r .object.sha)"
          echo "commit: $commit"
          tree="$(gh api /repos/$GITHUB_REPOSITORY/git/commits/$commit | jq -r .tree.sha)"
          echo "tree: $tree"
          elems="$(gh api /repos/$GITHUB_REPOSITORY/git/trees/$tree | jq -c '.tree | map({ "key": .path, "value": .sha }) | from_entries')"
          echo "elems: $elems"
          [ "$elems" == '{".gitmodules":"7816159e836aec22afcbcb75f56f706883890054","test0":"f398921287dae85b39c97f5273f8a8a9ebdc76d7","test1":"65d3b0bef66bfb952f14c70e22cbe78aa9613e97"}' ] && echo 'Success!'
